<a href="https://colab.research.google.com/github/Wenypb/Simulacion/blob/main/Tablero.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Ejemplo:

Supongamos que tenemos un tablero de 4 colores. Lanzamos dos monedas y avanzamos, en sentido horario, el número de caras que aparezcan. Si repetimos el procedimiento... ¿Son todos los sectores igual de probables cuando pase mucho tiempo?

$X_{n}$ probabilidad de estar en el sector naranja tras $n$ lanzamientos

$Y_{n}$ probabilidad de estar en el sector azul tras $n$ lanzamientos

$Z_{n}$ probabilidad de estar en el sector verde tras $n$ lanzamientos

$t_{n}$ probabilidad de estar en el sector rojo tras $n$ lanzamientos

In [1]:

import random as rnd
import math
import numpy as np
import matplotlib.pyplot as plt

In [12]:
#Determinar en que sector inicia
sector=rnd.random()
#Si 0<=sector<=0.25 comienza en naranja
if 0<sector<=0.25:
  Inicio=1
#Si 0<=sector<=0.25 comienza en azul
elif 0.25<sector<=0.5:
  Inicio=2
#Si 0<=sector<=0.25 comienza en verde
elif 0.5<sector<=0.75:
  Inicio=3
#Si 0<=sector<=0.25 comienza en rojo
elif 0.75<sector<=1:
  Inicio=4
print(Inicio)

2


In [ ]:
Función que determina el número de caras obtenidas en m lanzamientos

In [17]:
def Caras(lanzamientos):
  n=lanzamientos
  Caras=0
  for i in range(n):
    Moneda=rnd.random()
    if Moneda<=0.5:
      Caras=Caras+1
  return Caras

In [23]:
Ncaras=Caras(2)
print(Ncaras)

0


In [ ]:
#Determinar el número de repeticiones
n=10
lanzamientos=2
sector=Inicio
Resultados=[]
for i in range(n):
  Avanzar=Caras(lanzamientos)
if sector ==1:
if Avanzar==0:      sector=1    elif Avanzar==1:      sector=2    elif Avanzar==2:      sector=3  elif sector ==2:    if Avanzar==0:      sector=2    elif Avanzar==1:      sector=3    elif Avanzar==2:      sector=4  elif sector ==3:    if Avanzar==0:      sector=3    elif Avanzar==1:      sector=4    elif Avanzar==2:      sector=1  elif sector ==4:    if Avanzar==0:      sector=4    elif Avanzar==1:      sector=1    elif Avanzar==2:      sector=2  Resultados.append(sector)print(Resultados)

In [28]:
#Matriz de Transición
A=np.array([[0.25,0, 0.25,0.5],[0.5,0.25,0,0.25],[0.25,0.5,0.25,0],[0,0.25,0.5,0.25]])
#Probabilidades iniciales
X0=np.array([[0.25],[0.25],[0.25],[0.25]])
#Numero de repeticiones del ejercicio
n=10
#A a la n
An=A**n
print(An)
#Probabilidad tras n lanzamientos
Probabilidad=np.dot(An,X0)
print(Probabilidad)

[[9.53674316e-07 0.00000000e+00 9.53674316e-07 9.76562500e-04]
 [9.76562500e-04 9.53674316e-07 0.00000000e+00 9.53674316e-07]
 [9.53674316e-07 9.76562500e-04 9.53674316e-07 0.00000000e+00]
 [0.00000000e+00 9.53674316e-07 9.76562500e-04 9.53674316e-07]]
[[0.00024462]
 [0.00024462]
 [0.00024462]
 [0.00024462]]
